# Generated by Django 3.1.4 on 2020-12-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='session date')),
                ('guitar', models.CharField(choices=[('L', 'Gibson Les Paul'), ('T', 'Fender Telecaster'), ('S', 'Fender Stratocaster'), ('R', 'Rickenbacker')], default='Gibson Les Paul', max_length=1)),
                ('amp', models.CharField(choices=[('M', 'Marshall JCM800'), ('F', 'Fender Twin'), ('V', 'Vox AC-30'), ('O', 'Orange AD30')], default='Marshall JCM800', max_length=1)),
                ('notes', models.TextField(max_length=250)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.board')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='pedals',
            field=models.ManyToManyField(to='main_app.Pedal'),
        ),
    ]
