# Generated by Django 3.1.4 on 2020-12-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guitar', models.CharField(choices=[('L', 'Gibson Les Paul'), ('T', 'Fender Telecaster'), ('S', 'Fender Stratocaster'), ('R', 'Rickenbacker')], default='Gibson Les Paul', max_length=1)),
                ('amp', models.CharField(choices=[('M', 'Marshall JCM800'), ('F', 'Fender Twin'), ('V', 'Vox AC-30'), ('O', 'Orange AD30')], default='Marshall JCM800', max_length=1)),
                ('notes', models.TextField(max_length=250)),
                ('pedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pedal')),
            ],
        ),
    ]
