# Generated by Django 3.1.4 on 2020-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pedals',
            field=models.ManyToManyField(blank=True, to='main_app.Pedal'),
        ),
    ]
